/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Link = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'color' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'image' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LinkResponse = IDL.Record({ 'id' : IDL.Text, 'link' : Link });
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLink' : IDL.Func([IDL.Text, Link], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteLink' : IDL.Func([IDL.Text], [], []),
  'getAllLinks' : IDL.Func([], [IDL.Vec(LinkResponse)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLink' : IDL.Func([IDL.Text], [Link], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateLink' : IDL.Func([IDL.Text, Link], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Link = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'color' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'image' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LinkResponse = IDL.Record({ 'id' : IDL.Text, 'link' : Link });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLink' : IDL.Func([IDL.Text, Link], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteLink' : IDL.Func([IDL.Text], [], []),
    'getAllLinks' : IDL.Func([], [IDL.Vec(LinkResponse)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLink' : IDL.Func([IDL.Text], [Link], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateLink' : IDL.Func([IDL.Text, Link], [], []),
  });
};

export const init = ({ IDL }) => { return []; };